### ISSUE TITLE
DB 수정사항

### ISSUE THREAD

**Issue by khhandrea** [eco-coder/recycle-helper#14]
- 독극물이 들어있는 유리병 질문을 빼도 될 것 같습니다.
- 영수증의 재질을 답할 때, '-에요' → '-예요'
- 질문 끝에 전부 물음표 찍기
- 문장 끝에 전부 마침표 찍기
- 깨진 유리 결과 : 신문지로 감싼 후 종량제에 버리기

**Comment by KoreanThinker** [comment]
해당 내용 @khhandrea 님이 수정 가능하실까요?
DB 구조를 조금 변경했습니다.
기존의 string 타입이던 result를 아래와 같이 타입을 주게됬습니다.
```ts
export interface Result {
  name: string
  content: string
  image: string
}
```
name은 적당히 이해될정도로 작성하면 될것 같고 content는 채워져있습니다.
image도 png로 구하실수 있으면 부탁드리겠습니다. 

### image 규칙
1. 인터넷에서 배경 없는 사진 선정 .png 가능하면 정사각형
2. `public/images/result/` 밑에 사진 넣어주세요
3. 파일이름을 `사진1.png`라고 했다면 result.image에는 `사진1`이라고 작성해주시면 됩니다.
upstream이랑 fetch & pull 꼭 부탁드립니다 🙏
4. 이미지는 아래 사진 회색 공간에 들어갑니다.
![image](https://user-images.githubusercontent.com/48207131/134544832-b8919b7c-65a3-44cb-b13f-790adad9eff3.png)
