### ISSUE TITLE
첫화면, 결과화면

### ISSUE THREAD

**Issue by KoreanThinker** [eco-coder/recycle-helper#16]
## 결과화면
결과화면은 이런식으로 수정하면 될것 같습니다.
- 데스크탑 기준 왼쪽은 name, content 오른쪽 정사각형 사진 넘치면 object-fill: cover;
- 모바일 일자로
- 다시하기 버튼
![image](https://user-images.githubusercontent.com/48207131/134541062-957bfe2f-ce88-4b35-8d57-4f61c929d41e.png)
mainPage.modules.sass를 Home.modules.sass랑 ResultCard.modules.sass로 나누려다보니 아래처럼 됬습니다;; 두 sass파일 수정 부탁드립니다.
![image](https://user-images.githubusercontent.com/48207131/134541128-2afe511c-f8f9-410a-bca0-10dd501c8b87.png)

# 첫화면
위와 같은 이유로 아래처럼 됬습니다.
![image](https://user-images.githubusercontent.com/48207131/134541231-0de29631-3f91-4204-a8f9-863bf7af4944.png)

# 추가요청사항
- 결과창에 들어갈 이미지는 정사각형으로 잘라서 보내드리겠습니다.
- 다시하기 버튼 눌렀을때 onInit으로 callBack하는데 (page/index.tsx 118번째줄) 클릭시 맨 상단으로 올라가도록 부탁드리겠습니다.
- 코드를 좀 바꿨는데 https://github.com/eco-coder/recycle-helper/pull/17/files 이거 참고해주시면 될것 같습니다.
- 업스트림이랑 싱크 꼭 부탁드립니다 🙏

**Comment by YunInSoo** [comment]
sass 부분은 sass를 만드실때 자동 들여쓰기 문제라서, 제가 다시  'mainPage.sass' 복사해서 'Home.modules.sass,  ResultCard.modules.sass' 만들었습니다.
